version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: julio
      POSTGRES_DB: despesas
      POSTGRES_PASSWORD: julio
    ports:
      - 5432:5432
    volumes:
     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080