CREATE SCHEMA IF NOT EXISTS "julio_zeferino";
CREATE SCHEMA IF NOT EXISTS "warehouse";
CREATE SCHEMA IF NOT EXISTS "raw";
-- CREATE DATABASE IF NOT EXISTS metabase;
-- CREATE USER IF NOT EXISTS metabase WITH PASSWORD 'metabase';
-- GRANT ALL PRIVILEGES ON DATABASE metabase TO metabase;
