controller: trescoracoes-mg.portaltp.com.br/api/transparencia.asmx
method: GET
paths:
  empenhos: /json_empenhos
  liquidacoes: /json_liquidacoes
  pagamentos: /json_pagamentos
  diarias: /json_diarias
  obras: /json_obras
months: 2
bd:
  host: localhost
  user: julio
  password: julio
  schema: raw
  database: despesas
  port: 5432