config:
  debug: false

despesas:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: julio
      password: julio
      port: 5432
      dbname: despesas  # or database instead of dbname
      schema: julio_zeferino
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
    prod:
      type: postgres
      host: localhost
      user: julio
      password: julio
      port: 5432
      dbname: despesas  # or database instead of dbname
      schema: warehouse
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 2  # default 1 retry on error/timeout when opening connections
