config:
  debug: false

despesas:
  target: dev
  outputs:
    dev:
      type: postgres
      # host: dw
      # user: julio
      # password: julio
      # port: 5432
      # dbname: despesas
      host: "{{ env_var('DB_TCC_HOST') }}"
      user: "{{ env_var('DB_TCC_USER') }}"
      password: "{{ env_var('DB_TCC_PASS') }}"
      port: 5432
      dbname: "{{ env_var('DB_TCC_DBNAME') }}"
      schema: julio_zeferino
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
    prod:
      type: postgres
      host: "{{ env_var('DB_TCC_HOST') }}"
      user: "{{ env_var('DB_TCC_USER') }}"
      password: "{{ env_var('DB_TCC_PASS') }}"
      port: 5432
      dbname: "{{ env_var('DB_TCC_DBNAME') }}"
      schema: warehouse
      keepalives_idle: 0
      connect_timeout: 10
      retries: 2
